# Generated by Django 4.0.1 on 2022-04-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='tipo',
            field=models.CharField(choices=[('Aire', 'Aire'), ('Tierra', 'Tierra'), ('Mar', 'Mar')], default='tierra', max_length=6),
        ),
    ]
