# Generated by Django 4.0.1 on 2022-04-25 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0002_viajes_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('precio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('descripcion', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('Aire', 'Aire'), ('Tierra', 'Tierra'), ('Mar', 'Mar')], default='tierra', max_length=6)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.empresa')),
            ],
            options={
                'verbose_name_plural': 'Viajes',
            },
        ),
        migrations.DeleteModel(
            name='Viajes',
        ),
    ]
